///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ArticleActionNew {
/*
{
  "_id": "661a87424c935a1f72e162a1",
  "user_id": "66190f870e7afee6816351b4",
  "article_id": "661840465798402c806d1250",
  "is_liked": false,
  "is_disliked": false,
  "is_bookmarked": false,
  "is_viewed": true,
  "is_shared": true,
  "shared_count": 0,
  "createdAt": "2024-04-13T13:23:14.634Z",
  "updatedAt": "2024-04-15T06:05:26.850Z",
  "__v": 0
}
*/

  String? Id;
  String? userId;
  String? articleId;
  bool isLiked = false;
  bool isDisliked = false;
  int likes = 0;
  int dislikes = 0;
  int bookmarks = 0;
  bool isBookmarked = false;
  bool? isViewed;
  bool? isShared;
  int? sharedCount;
  String? createdAt;
  String? updatedAt;
  int? _V;

  ArticleActionNew({
    this.Id,
    this.userId,
    this.articleId,
    this.isLiked = false,
    this.isDisliked = false,
    this.likes = 0,
    this.dislikes = 0,
    this.bookmarks = 0,
    this.isBookmarked = false,
    this.isViewed,
    this.isShared,
    this.sharedCount,
    this.createdAt,
    this.updatedAt,
  });
  ArticleActionNew.fromJson(Map<String, dynamic> json) {
    print("");
    Id = json['_id']?.toString();
    userId = json['user_id']?.toString();
    articleId = json['article_id']?.toString();
    isLiked = json['is_liked'] ?? false;
    isDisliked = json['is_disliked'] ?? false;
    likes = json['likes'] ?? 0;
    dislikes = json['dislikes'] ?? 0;
    bookmarks = json['bookmarks'] ?? 0;
    isBookmarked = json['is_bookmarked'] ?? false;
    isViewed = json['is_viewed'];
    isShared = json['is_shared'];
    sharedCount = json['shared_count']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    _V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['user_id'] = userId;
    data['article_id'] = articleId;
    data['is_liked'] = isLiked;
    data['is_disliked'] = isDisliked;
    data['likes'] = likes;
    data['dislikes'] = dislikes;
    data['bookmarks'] = bookmarks;
    data['is_bookmarked'] = isBookmarked;
    data['is_viewed'] = isViewed;
    data['is_shared'] = isShared;
    data['shared_count'] = sharedCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = _V;
    return data;
  }
}
